#ifndef __MainFrameImpl__
#define __MainFrameImpl__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "gui.h"

/** Implementing MainFrame */
class MainFrameImpl : public MainFrame
{
public:
	/** Constructor */
	MainFrameImpl( wxWindow* parent );
};

#endif // __MainFrameImpl__
